os:
  - linux
  - osx

sudo: required
dist: trusty
osx_image: xcode7.3

language: cpp
compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - bash ./.travis-deps.sh

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cmake . -DLLVM_DIR=/usr/lib/llvm-3.9/lib/cmake/llvm ; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then cmake . -DLLVM_DIR=/usr/local/opt/llvm/lib/cmake/llvm ; fi
  - make -j 2
  - ctest --output-on-failure
